import jsPDF from "jspdf"
import type { HealthMetric } from "@/components/HealthDashboard"

// Enhanced: Robust PDF generator with comprehensive error handling
export function generatePDF(metric: HealthMetric) {
  try {
    const doc = new jsPDF()
    
    // Enhanced: Premium header with gradient effect simulation
    doc.setFillColor(20, 184, 166) // Teal
    doc.rect(0, 0, 210, 40, "F")
    
    // Logo/Title with better typography
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(26)
    doc.setFont("helvetica", "bold")
    doc.text("FlareHealth AI Vault", 105, 18, { align: "center" })
    doc.setFontSize(13)
    doc.setFont("helvetica", "normal")
    doc.text("Health Metric Report", 105, 28, { align: "center" })
    doc.text("Powered by Flare Network DePIN", 105, 35, { align: "center" })
    
    // Enhanced: Date & Time with timestamp
    doc.setFontSize(10)
    const now = new Date()
    doc.text(`Generated: ${now.toLocaleDateString()} at ${now.toLocaleTimeString()}`, 15, 50)
    
    // Enhanced: Patient Info (Customizable placeholder)
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(15)
    doc.setFont("helvetica", "bold")
    doc.text("Patient Information", 15, 65)
    
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text("Name: John Doe (Demo Patient)", 15, 73)
    doc.text("Patient ID: FH-2025-001", 15, 80)
    doc.text("Date of Birth: 01/15/1985 (Age: 40)", 15, 87)
    doc.text("Network: Flare Coston2 Testnet", 15, 94)
    
    // Enhanced: Metric Details with better formatting
    doc.setFontSize(17)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(20, 184, 166)
    doc.text(`${metric.label} Report`, 15, 110)
    
    // Reading box with border
    doc.setDrawColor(20, 184, 166)
    doc.setLineWidth(0.5)
    doc.roundedRect(15, 115, 180, 25, 3, 3, "S")
    
    doc.setTextColor(0, 0, 0)
    doc.setFontSize(13)
    doc.setFont("helvetica", "bold")
    doc.text(`Current Reading: ${metric.value} ${metric.unit}`, 20, 125)
    
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text(`Status: ${metric.status.toUpperCase()}`, 20, 132)
    doc.text(`Normal Range: ${metric.normalRange}`, 20, 138)
    
    // Enhanced: Divider with style
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.8)
    doc.line(15, 148, 195, 148)
    
    // Personalized Insights
    doc.setFontSize(15)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(20, 184, 166)
    doc.text("Personalized Insights", 15, 158)
    
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(0, 0, 0)
    const insights = getInsights(metric)
    let yPos = 168
    insights.forEach((insight, idx) => {
      const lines = doc.splitTextToSize(`${idx + 1}. ${insight}`, 180)
      doc.text(lines, 15, yPos)
      yPos += lines.length * 6
    })
    
    // Recommendations
    doc.setFontSize(15)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(20, 184, 166)
    doc.text("Medical Recommendations", 15, yPos + 10)
    
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(0, 0, 0)
    const recommendations = getRecommendations(metric)
    yPos += 20
    recommendations.forEach((rec, idx) => {
      const lines = doc.splitTextToSize(`${idx + 1}. ${rec}`, 180)
      doc.text(lines, 15, yPos)
      yPos += lines.length * 6
    })
    
    // 30-Day Trend Summary
    doc.setFontSize(15)
    doc.setFont("helvetica", "bold")
    doc.setTextColor(20, 184, 166)
    doc.text("30-Day Trend Summary", 15, yPos + 10)
    
    doc.setFontSize(10)
    doc.setFont("helvetica", "normal")
    doc.setTextColor(0, 0, 0)
    const trendSummary = getTrendSummary(metric)
    doc.text(doc.splitTextToSize(trendSummary, 180), 15, yPos + 20)
    
    // Enhanced: Footer with disclaimer
    doc.setFontSize(8)
    doc.setTextColor(100, 100, 100)
    doc.setFont("helvetica", "italic")
    doc.text("This report is generated by FlareHealth AI Vault powered by Flare Network", 105, 275, { align: "center" })
    doc.text("For medical advice, please consult with your healthcare provider", 105, 280, { align: "center" })
    doc.setFont("helvetica", "bold")
    doc.text("⚠️ This is a demonstration report with sample data", 105, 285, { align: "center" })
    
    // Enhanced: Save PDF with detailed filename
    const fileName = `FlareHealth_${metric.label.replace(/\s+/g, "_")}_Report_${now.toISOString().split("T")[0]}_${now.getHours()}${now.getMinutes()}.pdf`
    doc.save(fileName)
    
    return true
  } catch (error) {
    console.error("PDF Generation Error:", error)
    throw new Error("Failed to generate PDF report")
  }
}

function getInsights(metric: HealthMetric): string[] {
  const insights: Record<string, string[]> = {
    "heart-rate": [
      `Your current heart rate of ${metric.value} ${metric.unit} is within the normal resting range.`,
      "Heart rate variability indicates good cardiovascular health and stress management.",
      "Regular monitoring helps detect early signs of arrhythmias or other cardiac conditions."
    ],
    "temperature": [
      `Your body temperature of ${metric.value}°C is within the normal range.`,
      "Stable body temperature indicates proper metabolic function and absence of infection.",
      "Temperature fluctuations can be early indicators of illness or hormonal changes."
    ],
    "blood-pressure": [
      `Your blood pressure reading of ${metric.value} ${metric.unit} is optimal.`,
      "Maintaining healthy blood pressure reduces risk of heart disease and stroke.",
      "Consistent monitoring is crucial for early detection of hypertension."
    ],
    "blood-oxygen": [
      `Your SpO2 level of ${metric.value}% indicates excellent oxygen saturation.`,
      "Optimal oxygen levels ensure proper organ function and tissue oxygenation.",
      "Continuous monitoring is especially important for respiratory conditions."
    ],
    "respiratory": [
      `Your respiratory rate of ${metric.value} ${metric.unit} is within normal limits.`,
      "Regular breathing patterns indicate healthy lung function.",
      "Changes in respiratory rate can signal respiratory distress or metabolic issues."
    ],
    "mental-health": [
      `Your mental health score of ${metric.value}/100 indicates ${metric.status} psychological well-being.`,
      "Regular mood tracking helps identify patterns and triggers.",
      "Mental health is as important as physical health for overall wellness."
    ]
  }
  
  return insights[metric.id] || ["No specific insights available for this metric."]
}

function getRecommendations(metric: HealthMetric): string[] {
  const recommendations: Record<string, string[]> = {
    "heart-rate": [
      "Continue regular cardiovascular exercise to maintain heart health.",
      "Practice stress-reduction techniques like meditation or deep breathing.",
      "Monitor your heart rate during different activities to understand your baseline.",
      "Consult a cardiologist if you notice irregular heartbeats or chest discomfort."
    ],
    "temperature": [
      "Maintain adequate hydration to support thermoregulation.",
      "Monitor temperature changes during illness or immune response.",
      "Contact a healthcare provider if fever persists above 38.5°C (101.3°F).",
      "Keep a temperature log if experiencing unexplained fluctuations."
    ],
    "blood-pressure": [
      "Maintain a low-sodium diet to support healthy blood pressure.",
      "Engage in regular physical activity (150 minutes/week recommended).",
      "Monitor blood pressure at the same time daily for consistency.",
      "Discuss medication options with your doctor if readings are consistently elevated."
    ],
    "blood-oxygen": [
      "Practice deep breathing exercises to optimize oxygen intake.",
      "Ensure proper ventilation in your living and working spaces.",
      "Monitor SpO2 during physical activity to understand your capacity.",
      "Seek immediate medical attention if SpO2 drops below 90%."
    ],
    "respiratory": [
      "Practice diaphragmatic breathing to strengthen respiratory muscles.",
      "Avoid exposure to air pollutants and allergens when possible.",
      "Stay active to maintain lung capacity and respiratory efficiency.",
      "Contact a healthcare provider if you experience shortness of breath or rapid breathing."
    ],
    "mental-health": [
      "Maintain a consistent sleep schedule for optimal mental health.",
      "Engage in regular social activities and maintain meaningful connections.",
      "Practice mindfulness or meditation for stress management.",
      "Consider professional counseling if experiencing persistent mood changes."
    ]
  }
  
  return recommendations[metric.id] || ["Please consult with your healthcare provider for personalized recommendations."]
}

function getTrendSummary(metric: HealthMetric): string {
  const recentData = metric.trendData.slice(-7)
  const olderData = metric.trendData.slice(-30, -7)
  
  const recentAvg = recentData.reduce((sum, d) => sum + d.value, 0) / recentData.length
  const olderAvg = olderData.reduce((sum, d) => sum + d.value, 0) / olderData.length
  
  const change = ((recentAvg - olderAvg) / olderAvg) * 100
  const trend = change > 2 ? "increasing" : change < -2 ? "decreasing" : "stable"
  
  return `Over the past 30 days, your ${metric.label.toLowerCase()} has been ${trend}. ` +
         `The average for the last 7 days (${recentAvg.toFixed(1)}) compared to the previous 23 days (${olderAvg.toFixed(1)}) ` +
         `shows a ${Math.abs(change).toFixed(1)}% ${change > 0 ? "increase" : "decrease"}. ` +
         `This trend is ${metric.status === "normal" || metric.status === "excellent" || metric.status === "good" ? "within expected ranges" : "worth monitoring closely"}.`
}